import booksMetadata from './books-metadata.json';
import { bookOverrides } from './books-config';

export interface BookItem {
  id: string;
  title: string;
  author: string;
  year: number;
  note: string;
  goodreadsUrl: string;
  rating: number;
  ratingsCount: number;
  pages: number;
  genres: string[];
  tags: string[];
  publisher: string;
  description: string;
  coverUrl: string;
}

// Logging for development
const isDev = process.env.NODE_ENV === 'development';
const log = (...args: any[]) => isDev && console.log('[BOOKS]', ...args);

log('[INFO] Loading books from metadata...');
log(`Found ${booksMetadata.length} books in metadata`);

/**
 * Array of books loaded from Goodreads metadata with applied overrides.
 * Books are loaded from books-metadata.json (generated by scraper) and
 * can be customized via bookOverrides in books-config.ts.
 * 
 * @see books-metadata.json - Source metadata from Goodreads scraper
 * @see books-config.ts - Manual overrides and configuration
 */
export const books: BookItem[] = booksMetadata.map((book: any, index: number) => {
  const overrides = bookOverrides[book.goodreadsUrl] || {};
  const hasOverrides = Object.keys(overrides).length > 0;
  
  if (hasOverrides) {
    log(`Applying overrides to book ${index + 1}:`, { url: book.goodreadsUrl, overrides });
  }
  
  return {
    id: book.id,
    title: book.title || 'Unknown Title',
    author: book.author || 'Unknown Author',
    year: overrides.year || book.year || new Date().getFullYear(),
    note: overrides.note || book.description?.substring(0, 100) || '',
    goodreadsUrl: book.goodreadsUrl,
    rating: book.rating || 0,
    ratingsCount: book.ratingsCount || 0,
    pages: book.pages || 0,
    genres: book.genres || [],
    tags: overrides.tags || book.tags || [],
    publisher: book.publisher || '',
    description: book.description || '',
    coverUrl: book.coverUrl || '',
  };
});

log(`[SUCCESS] Loaded ${books.length} books successfully`);

// Extract unique values for filtering
export const allGenres = Array.from(new Set(books.flatMap(book => book.genres))).sort();
export const allTags = Array.from(new Set(books.flatMap(book => book.tags))).sort();

log(`Found ${allGenres.length} unique genres:`, allGenres);
log(`Found ${allTags.length} unique tags:`, allTags);
